### ISSUE TITLE
Remove block break and mining cooldown module

### ISSUE THREAD

**Issue by erxson** [connorslade/SigmaUtils#13]
like in [ipn rejects](https://www.curseforge.com/minecraft/mc-mods/ipn-rejects). Source [here](https://github.com/blackd/IPN-Rejects/blob/master/platforms/fabric-1.19/src/main/java/org/anti_ad/mc/ipnrejects/cheats/mixin/MixinClientPlayerInteractionManager.java).

**Comment by connorslade** [comment]
Sure!
