### ISSUE TITLE
Config GUI Scale

### ISSUE THREAD

**Issue by connorslade** [connorslade/SigmaUtils#6]
This idea is bad, or at least current implementation. Module should be scraped. Maybe ill get around to a replacement at some point.

- [x] Remove the scale module
- [x] Remove usage of it within some custom graphics components

**Comment by erxson** [comment]
Are you going to fix scaling in the near future?

**Comment by connorslade** [comment]
Defiantly. This implementation was just a mess, so I decided it was best to just remove it and reimplement it later.
